config/routes.rb
Rails.application.routes.draw do
  
  

  resources :feeds, except: [:show, :edit, :update]
  
  get 'clusters/:id', to: 'clusters#show', as: 'cluster'
  
  root "static_page#home"
  

end

app/models/article.rb
# TODO να προσθέσω των αριθμό των φορών που συναντιέται κάθε λέξη στη βάση
# TODO να αρχικοποιείται με το κατέβασμα του άρθρου

class Article < ActiveRecord::Base
  before_validation :remove_queries_from_url
  
  validates :url, presence: :true, uniqueness: true
  validate :article_should_be_readable
  validate :article_should_not_be_small
  # το πιο πάνω θα μπορεί να ελέγχει
  #   το xml αν έχει κάποιο περιεχόμενο εναλλαχτικά
  before_save :default_values
  
  private

  ######################################
  # Επιστρέφει true αν το άρθο
  #  είναι αναγνώσιμα από την εφαρμογή
  def article_should_be_readable
    if (Pismo::Document.new(self.url).body.blank? == true)
      errors.add(:url, "δεν είναι αναγνώσιμο")
    end

  end

  def article_should_not_be_small
    if (Pismo::Document.new(self.url).body.split.length < 200)
      errors.add(:url, "είναι μικρό κείμενο")
    end

  end


  ########################################
  # Επιστρέφει το url χωρίς ορίσματα
  #   μετά το path. Είναι διαφορετικό
  #   από αυτό του feeds_helper.
  def remove_queries_from_url
    self.url.lstrip!
    self.url.rstrip!
    uri = URI.parse(self.url)
    self.url = "#{uri.scheme}://#{uri.host}#{uri.path}"
  end
  
  
  def default_values
    doc = Pismo::Document.new(self.url)
    self.title ||= doc.title.split("|").first # split μόνο για the guardian
    self.published_at ||= doc.datetime
    self.body = doc.body.gsub(/[^0-9A-Za-z .;,!?]/, '')
    w = WhatLanguage.new(:all)
    self.language = w.language(self.body).to_s
    
  end

end

app/models/cluster.rb
class Cluster < ActiveRecord::Base  
  belongs_to :model
  
  
  private

  
end

app/models/feed.rb
class Feed < ActiveRecord::Base
  before_validation :strip_url
  before_validation :lowercase
  
  validates :url, length: {maximum: 255}
  validates :url, presence: :true, uniqueness: true
  validate :url_should_response
  validate :string_has_uri_regexp
  
  before_save :default_values

  def get_links
    f = Feedjira::Feed.fetch_and_parse(self.url)
    urls = []
    f.entries.each { |e|
      e.url.lstrip!
      e.url.rstrip!
      e.url.downcase!
      uri = Addressable::URI.parse(e.url)
      url = "#{uri.scheme}://#{uri.host}#{uri.path}"
      urls << url
    }
    return urls
  end

  def get_new_articles
    f = Feedjira::Feed.fetch_and_parse(self.url)
    urls = []
    f.entries.each { |e|
      e.url.lstrip!
      e.url.rstrip!
      e.url.downcase!
      uri = Addressable::URI.parse(e.url)
      url = "#{uri.scheme}://#{uri.host}#{uri.path}"
      urls << url
    }
    old = Article.pluck(:url).flatten.uniq
    new_urls = urls.sort.uniq - old 
    return new_urls
  end
  
  private
  def strip_url
    if(self.url)
      self.url.lstrip!
      self.url.rstrip!
    end
  end

  def lowercase
    if self.url
      self.url.downcase!
    end
  end

  ########################################################
  # Ελέγχεται με το μέγεθος της απάντησης του ping
  # θα μπορούσε εδώ να εκμεταλλεύεται περισσότερες πληροφορίες
  # από την απάντηση.
  def url_should_response
    if ( (self.url) &&
         (self.url  =~ /\A#{URI::regexp(['http', 'https'])}\z/) &&
         (`ping -c 1 #{URI.parse(self.url).host}`.length == 0))
      errors.add(:url, "δεν ανταποκρίνεται, υπάρχει;")
    end
  end
  
  #########################################################
  # regex from stackoverflow and it seems ok
  # http://stackoverflow.com/questions/1805761/check-if-url-is-valid-ruby
  def string_has_uri_regexp
    if !(url =~ /\A#{URI::regexp(['http', 'https'])}\z/)
      errors.add(:url, "δεν έχει τη κανονική μορφή uri")
    end
  end

  def default_values
    self.name ||= Feedjira::Feed.fetch_and_parse(self.url).title
    self.fetched_at ||= Date.new
  end
end

app/models/model.rb
class Model < ActiveRecord::Base
  has_many :clusters
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :set_locale, :init_clusters
  
  def set_locale
    I18n.locale = params[:locale] || I18n.default_locale
  end
  
  def init_clusters
    @clusters = Cluster.where(model_id: Model.last.id)  # .where('number_of_documents >= 5')
  end
end

app/controllers/clusters_controller.rb
class ClustersController < ApplicationController
  
  def index
  end
  
  def show
    @cluster = Cluster.find(params[:id])
    @keywords = JSON.parse(@cluster.keywords)
    articles_urls = JSON.parse(@cluster.articles_urls)
    @articles = Article.where(:url => articles_urls)
  end
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  include FeedsHelper
  before_action :set_feed, only: [:show, :edit, :update, :destroy]

  # GET /feeds
  # GET /feeds.json
  def index
    @feeds = Feed.paginate(page: params[:page], :per_page => 10)
  end

  # GET /feeds/1
  # GET /feeds/1.json

  def show
  end
  
  # GET /feeds/new
  def new
    @feed = Feed.new
  end

  # GET /feeds/1/edit
  def edit
  end

  # TODO το submit δεν δουλεύει
  # POST /feeds
  # POST /feeds.json
  def create
    @feed = Feed.new
    respond_to do |format|
      @new_url = feed_params[:url]
      if ((Feed.new(feed_params).valid?) &&
          # (@new_url = remove_query_from_url(@new_url)) &&
          (is_xml? @new_url) &&
          ((@feed = Feed.new(:url => @new_url)).save))
        format.html { redirect_to feeds_url, notice: 'Έχετε Εγγραφεί στο Κανάλι με επιτυχία' }
        format.json { render :show, status: :created, location: feeds_url }
      else
        format.html { render :new }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
  end


  

  # PATCH/PUT /feeds/1
  # PATCH/PUT /feeds/1.json

  def update
=begin
    respond_to do |format|
      if @feed.update(feed_params)
        format.html { redirect_to @feed, notice: 'Feed was successfully updated.' }
        format.json { render :show, status: :ok, location: @feed }
      else
        format.html { render :edit }
        format.json { render json: @feed.errors, status: :unprocessable_entity }
      end
    end
=end
  end
  
  # DELETE /feeds/1
  # DELETE /feeds/1.json
  def destroy
    @feed.destroy
    redirect_to(:back)
    respond_to do |format|
      format.html { redirect_to feeds_url, notice: 'To Κανάλι έχει διαγραφεί με επιτυχία' }
      format.json { head :no_content }
    end
    
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_feed
    @feed = Feed.find(params[:id])
  end
  
  # Never trust parameters from the scary internet, only allow the white list through.
  def feed_params
    params.require(:feed).permit(:url)
  end
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def home
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/clusters_helper.rb
module ClustersHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper

  #####################################
  # αφήνει μόνο το http ή https, host 
  #   και το path
  def remove_query_from_url(url)
    uri = URI.parse(url)
    return "#{uri.scheme}://#{uri.host}#{uri.path}"
  end


  ##############################################
  # επιστρέφει true όταν το url απαντά
  #   200-OK σε http αίτημα
  def is_http_ok? url
    uri = URI.parse(url)
    res = Net::HTTP.get_response(uri)
    res.code == '200'
  end

  ######################################
  # επιστρέφει true εαν η πρώτη γραμμή
  #   περιέχει τη λέξη xml
  # TODO: έλεγχος δομής xml αν είναι RSS/ATOM
  def is_xml? url
    uri = URI.parse(url)
    res = Net::HTTP.get_response(uri)   
    res.body.lines.first.to_s.include? "xml"
  end
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/clusters/show.html.erb
<%- model_class = Cluster -%>
<div class="page-header">
  <h2><% @keywords.each do |keyword|  %>
    #<%= keyword %>
    <% end %>
  </h2>
</div>
<ul>
  <% @articles.each do |article| %>
  <header>
    <h2>
      <a target="_blank" href="<%= article.url %>">
	<%= article.title %>
      </a>
    </h2>
    <span> <%= URI.parse(article.url).host  %></span>
  </header>
  <div>
    <p>
      <%= article.body.split[0...70].join(' ') %>...
    </p>
    <a target="_blank" href="<%= article.url %>">Read more</a>
  </div>
  <hr>

  <% end %>
  
</ul>

app/views/feeds/_form.html.erb
<%= form_for @feed, :html => { :class => "form-horizontal feed" } do |f| %>

  <% if @feed.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@feed.errors.count, "error") %> prohibited this feed from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @feed.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <!--div class="form-group">
    <%= f.label :name, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <%=f.error_span(:name) %>
  </div-->
  <div class="form-group">
    <%= f.label :url, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :url, :class => 'form-control' %>
    </div>
    <%=f.error_span(:url) %>
  </div>
  <!--div class="form-group">
    <%= f.label :fetched_at, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :fetched_at, :class => 'form-control' %>
    </div>
    <%=f.error_span(:fetched_at) %>
  </div-->

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                feeds_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/feeds/edit.html.erb
<!--%- model_class = Feed -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %-->

app/views/feeds/index.html.erb
<%- model_class = Feed -%>
<div class="page-header">
  <h1>Κανάλια<!--%=t '.title', :default => model_class.model_name.human.pluralize.titleize %--></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:url) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
</tr>
</thead>
<tbody>
  <%= will_paginate%>
  <% @feeds.each do |feed| %>
  <tr>
    <td><%= feed.name %></td>
    <td><%= feed.url %></td>
    <td>
      <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
      feed_path(feed),
      :method => :delete,
      :class => 'btn btn-xs btn-danger' %>
     <!-- :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
      -->
    </td>
  </tr>
  <% end %>
</tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
new_feed_path,
:class => 'btn btn-primary' %>

app/views/feeds/new.html.erb
<%- model_class = Feed -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/feeds/show.html.erb
<!--%- model_class = Feed -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @feed.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:url) %>:</strong></dt>
  <dd><%= @feed.url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:fetched_at) %>:</strong></dt>
  <dd><%= @feed.fetched_at %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              feeds_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_feed_path(@feed), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              feed_path(@feed),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="el">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Καφενές" %></title>
    <%= csrf_meta_tags %>
    
    <%= stylesheet_link_tag "application", :media => "all" %>
    
    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
	<![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Καφενές</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "Τα Κανάλια μοu", feeds_path  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <!--div class="row"-->
      <div class="col-lg-9">
        <%= bootstrap_flash %>
        <%= yield %>
      </div>
      <!--/div--><!--/.row -->
      <!--div class="row"-->
      <div class="col-lg-3">
	<div class="well sidebar-nav">
	  <ul class="nav nav-list">
	    <li class="nav-header">Τα τελευταία Νέα</li>
	    <% @clusters.order(number_of_documents: :desc).each do |cluster| %>
	    <% string_to_show = "#{JSON.parse(cluster.keywords).first} (#{cluster.number_of_documents})" %>
	    <li><%= link_to string_to_show  , cluster_path(cluster) %></li>
	    <% end %>
	  </ul>
	</div><!--/.well -->
      </div><!--/.col-lg-3-->  
      <!--/div--><!--/row-->
    </div><!--/container-->
      
      
      <footer>
        <p>&copy; Πανεπιστήμιο Κύπρου - Τμήμα Πληροφορικής - 2016</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/static_pages/home.html.erb
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>